### ISSUE TITLE
Usage proposal

### ISSUE THREAD

**Issue by a-type** [tato123/react-grits#2]
I've been experimenting with this on my personal project.

There are some parts of the usage which I feel could be streamlined with a few tricks. Interested in your thoughts on it.

## 1: Docs: Encourage users to define template areas in a visual manner.

Template area definitions in CSS encourage you to think visually by making you use multiple lines. It might be nice for the documentation to encourage that as well here by suggesting defining the template areas as a standalone variable.

As a newcomer to CSS Grid, it wasn't until I went back and read MDN docs and saw their template area usage that I recognized what exactly the nested arrays were supposed to mean.

```js
const templateAreas = [
     ['head', 'head'],
     ['nav', 'main'],
     ['nav', 'foot'],
];
const ExampleLayout = ({ children, ...rest }) => {
     /* .. etc .. */
     return (
          <Grid 
            templateAreas={templateAreas}
          >
     /* ... etc ... */
};
```

## 2. Enable pass-through grid area assignment from children

One of the issues I have with current usage is that child order can seem too convention-based and opaque. It's not immediately apparent to the user of a Layout A) which child will be assigned to which area (especially when areas are arranged in a non-linear manner) and B) how many children should be provided. Both of these could be explained in the documentation of a layout component, but I think it might be better to push the assignment of areas onto the user.

Here's an idea of usage:

```js
import Layout from 'react-grits';
import ExampleLayout from './ExampleLayout';

/* ... */

<Layout component={ExampleLayout}>
     <Head gridArea="head" />
     <Foot gridArea="foot" />
     <Nav gridArea="nav" />
    <Article gridArea="main" />
</Layout>
```

(note, perhaps just plain 'area', or 'role', or some other more idiomatic prop name could be used to further abstract the fact that CSS Grid is powering this)

Now the only documentation necessary is for ExampleLayout to present the names of its areas to the user, which I think is reasonable to expect. End result, the layout user's code looks nice and easy to follow, and the layout user doesn't have to be concerned with child ordering, freeing them to make semantic decisions in that regard.

That may be going against your intentions with the library, though. If a user did want a convention-based assignment, they could still do things as they're done now; so this is really just a feature added.

This should be doable by assigning `child.props.gridArea` to GridItem when it's created.

The other nice thing is that our layout component can be streamlined...

```js
const templateAreas = [
     ['head', 'head'],
     ['nav', 'main'],
     ['nav', 'foot'],
];
const ExampleLayout = ({ children, ...rest }) => {
     return (
          <Grid 
            templateAreas={templateAreas}
            templateRows="10% 90% 10%"
            templateColumns="10% 90%"
          >
               {createGridItemsForChildren(children)}
          </Grid>
     );
};
```

## 3: Last mile

Just based on that streamlining, I imagine you could get to a layout component definition syntax which was just assigning props to a Grid component, if you moved the `createGridItemsForChildren` usage inside the Grid component itself.

```js
const templateAreas = [
     ['head', 'head'],
     ['nav', 'main'],
     ['nav', 'foot'],
];

export default withProps({
     templateAreas,
     templateRows: '10% 90% 10%',
     templateColumns: '10% 90%',
})(Grid);
```

This is starting to feel a lot like using CSS Grid... except I think there's benefit in that we have made layout relationships more exposed in the code instead of hiding them in CSS somewhere. Plus all the cool debugging tools.

That would break the current usage, though, preventing users from doing order-based area assignments if that was their preference. A user could work around that by mapping `gridArea` props to children as a composed wrapper, or a `childAreas` array could be accepted on `Grid` which automatically assigns the areas in order to incoming children.

Just spitballing now. Thoughts?

**Comment by tato123** [comment]
> 1: Docs: Encourage users to define template areas in a visual manner.

I agree with your suggestion, visually that is easier to read. 

> 2. Enable pass-through grid area assignment from children

I had been going back and fourth on `gridArea`. Prior to using gridItem I was directly placing the children in, I do like the idea of being more explicit. It would simplify things. I'll try to make this update.

**Comment by tato123** [comment]
Library has been updated
